version: '3'  
services:  
  lottery-mysql:  
    image: mysql:5.7.43  
    container_name: lottery-mysql  
    restart: always  
    environment:  
      MYSQL_ROOT_PASSWORD: root  
    volumes:  
      - ./mysql-data:/var/lib/mysql 
    ports:  
      - "9106:3306"  

  lottery-rabbitmq:  
    image: rabbitmq:3.6.10-management  
    container_name: lottery-rabbitmq  
    restart: always  
    ports:  
      - "9104:15672"  
      # - "9106:5672"  
  lottery-redis:  
    image: redis:6.0.6  
    container_name: lottery-redis  
    restart: always  
    # ports:  
    #   - "9107:6379"  
  lottery-api:  
    image: api:0.0.1-SNAPSHOT  
    container_name: lottery-api  
    restart: always  
    ports:  
      - "9102:9001" 
    depends_on:  
      - lottery-mysql  
      - lottery-rabbitmq  
      - lottery-redis 
    links:  
      - lottery-mysql  
      - lottery-rabbitmq  
      - lottery-redis  
    environment:  
      spring.datasource.url: jdbc:mysql://lottery-mysql/prize?useUnicode=true&characterEncoding=utf-8  
      spring.datasource.username: prize  
      spring.datasource.password: prize  
      spring.rabbitmq.host: lottery-rabbitmq
      spring.rabbitmq.port: 5672
      spring.redis.host: lottery-redis
      spring.redis.port: 6379
  lottery-msg:  
    image: msg:0.0.1-SNAPSHOT  
    container_name: lottery-msg  
    restart: always  
    links:  
      - lottery-mysql  
      - lottery-rabbitmq  
      - lottery-redis 
    depends_on:  
      - lottery-mysql  
      - lottery-rabbitmq  
      - lottery-redis 
    environment:  
      spring.datasource.url: jdbc:mysql://lottery-mysql/prize?useUnicode=true&characterEncoding=utf-8  
      spring.datasource.username: prize  
      spring.datasource.password: prize  
      spring.rabbitmq.host: lottery-rabbitmq
      spring.rabbitmq.port: 5672
      spring.redis.host: lottery-redis
      spring.redis.port: 6379
    
  lottery-backend:  
    image: backend:0.0.1-SNAPSHOT  
    container_name: lottery-backend  
    restart: always 
    ports:  
      - "9103:8080"       
    volumes:  
      - ./backend-upload:/usr/local/tomcat/webapps/ROOT/upload  
    links:  
      - lottery-mysql  
    depends_on:  
      - lottery-mysql  

  lottery-nginx:  
    image: nginx:1.16.1  
    container_name: lottery-nginx  
    restart: always  
    ports:  
      - "9101:80"  
    volumes:  
      - ./nginx-conf:/etc/nginx/conf.d
      - ./nginx-h5:/usr/share/nginx/html
      - ./backend-upload:/usr/share/nginx/html/upload   
    links:  
      - lottery-api  
    depends_on:  
      - lottery-api  

   