version: '3'  
services:  
  lottery-mysql:  
    image: mysql:5.7.43  
    container_name: lottery-mysql  
    restart: always  
    environment:  
      MYSQL_ROOT_PASSWORD: root  
    volumes:  
      - ./mysql-data:/var/lib/mysql 
      - ./docker-compose-init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:  
      - "9106:3306"  
    networks:  
      - lottery_net

  lottery-rabbitmq:  
    image: rabbitmq:3.6.10-management  
    container_name: lottery-rabbitmq  
    restart: always  
    ports:  
      - "9104:15672"  
    networks:  
      - lottery_net

  lottery-redis:  
    image: redis:6.0.6  
    container_name: lottery-redis  
    restart: always  
    networks:  
      - lottery_net

  lottery-nginx:  
    image: nginx:1.16.1  
    container_name: lottery-nginx  
    restart: always  
    ports:  
      - "9101:80"  
    volumes:  
      - ./nginx-conf:/etc/nginx/conf.d
      - ./nginx-h5:/usr/share/nginx/html
      - ./backend-upload:/usr/share/nginx/html/upload   
    networks:  
      - lottery_net

networks:  
  lottery_net:  
    driver: bridge  
    ipam:  
      config:  
        - subnet: 172.18.0.0/24  
   