version: '3'  
services:  
  lottery-mysql:  
    image: mysql:5.7.43  
    container_name: lottery-mysql  
    restart: always  
    environment:  
      MYSQL_ROOT_PASSWORD: root  
    volumes:  
      - ./mysql-data:/var/lib/mysql 
      - ./docker-compose-init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:  
      - "9106:3306"  
    networks:  
      - lottery_net

  lottery-rabbitmq:  
    image: rabbitmq:3.6.10-management  
    container_name: lottery-rabbitmq  
    restart: always  
    networks:  
      - lottery_net

  lottery-redis:  
    image: redis:6.0.6  
    container_name: lottery-redis  
    restart: always  
    networks:  
      - lottery_net

  lottery-api:  
    image: api:0.0.1-SNAPSHOT  
    container_name: lottery-api  
    restart: always  
    ports:  
      - "9102:8080" 
    depends_on:  
      - lottery-mysql  
      - lottery-rabbitmq  
      - lottery-redis 
    links:  
      - lottery-mysql  
      - lottery-rabbitmq  
      - lottery-redis  
    environment:
      server.port: 8080
      spring.datasource.url: jdbc:mysql://lottery-mysql/prize?useUnicode=true&characterEncoding=utf-8  
      spring.datasource.username: root  
      spring.datasource.password: root  
      spring.rabbitmq.host: lottery-rabbitmq
      spring.rabbitmq.port: 5672
      spring.redis.host: lottery-redis
      spring.redis.port: 6379
    networks:  
      - lottery_net

  lottery-msg:  
    image: msg:0.0.1-SNAPSHOT  
    container_name: lottery-msg  
    restart: always  
    links:  
      - lottery-mysql  
      - lottery-rabbitmq  
      - lottery-redis 
    depends_on:  
      - lottery-mysql  
      - lottery-rabbitmq  
      - lottery-redis 
    environment:
      server.port: 8080 
      spring.datasource.url: jdbc:mysql://lottery-mysql/prize?useUnicode=true&characterEncoding=utf-8  
      spring.datasource.username: root  
      spring.datasource.password: root  
      spring.rabbitmq.host: lottery-rabbitmq
      spring.rabbitmq.port: 5672
      spring.redis.host: lottery-redis
      spring.redis.port: 6379
    networks:  
      - lottery_net

  lottery-backend:  
    image: backend:0.0.1-SNAPSHOT  
    container_name: lottery-backend  
    restart: always 
    ports:  
      - "9103:8080"       
    volumes:  
      - ../backend/src/main/webapp/upload:/usr/local/tomcat/webapps/ROOT/upload:rw
    links:  
      - lottery-mysql  
    depends_on:  
      - lottery-mysql  
    networks:  
      - lottery_net

  lottery-nginx:  
    image: nginx:1.16.1  
    container_name: lottery-nginx  
    restart: always  
    ports:  
      - "9101:80"  
    volumes:  
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../h5:/usr/share/nginx/html
      - ../backend/src/main/webapp/upload:/usr/share/nginx/html/upload:rw
    depends_on:  
      - lottery-api  
    networks:  
      - lottery_net

networks:  
  lottery_net:  
    driver: bridge  
    ipam:  
      config:  
        - subnet: 172.18.0.0/24  


